# fly.toml app configuration file generated for recipe-collections on 2023-11-14T21:11:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipe-collections"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  LOG_LEVEL = "debug"